[tool.poetry]
name = "cloudlydb"
<<<<<<< HEAD
version = "2.0.0-alpha.6"
=======
version = "0.1.11"
>>>>>>> c215111 (Add support for update conditionals)
description = ""
authors = ["Nana Duah <gabano2005@gmail.com>"]
readme = "README.md"
packages = [{include = "cloudlydb"}]

[tool.poetry.dependencies]
python = ">=3.9 <4.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
boto3 = "^1.26.163"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
