name: Run Tests
run-name: Testing ${{ github.head_ref }} by @${{ github.actor }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"

      - run: poetry install
      - run: poetry run pytest -rP
